Adding client class
rionamcglinchey/Bew pull request #7
Opened 2023-10-11 13:25 UTC by OdhranHague

2023-10-11 13:26 UTC, johnmcg23 approved these changes

2023-10-11 13:46 UTC, lullabelle requested changes
add a description into the Pull requests and what part of the project spec it refers to!

2023-10-11 14:02 UTC, lullabelle approved these changes
approved

2023-10-12 08:12 UTC, lullabelle approved these changes

2023-10-12 08:29 UTC, merged